# Copyright 2024 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only
version: '3'

services:
  beacon-stub:
    image: ghcr.io/sprintertech/beacon-api-stub
    volumes:
      - "./stubs:/stubs"
    ports:
      - 8882:8882 # STUB
    environment:
      - STUB_DATA=/stubs/beacon.yml

  evm1:
    image: ghcr.io/sprintertech/sygma-x-solidity:1
    container_name: evm1
    command: "--db data/ -h 0.0.0.0 -p 8545 --wallet.mnemonic 'myth like bonus scare over problem client lizard pioneer submit female collect'"
    ports:
      - "8545:8545"
  evm2:
    image: ghcr.io/sprintertech/sygma-x-solidity:2
    command: "--db data/ -h 0.0.0.0 -p 8545 --wallet.mnemonic 'myth like bonus scare over problem client lizard pioneer submit female collect'"
    container_name: evm2
    ports:
      - "8645:8545"

  inclusion-prover:
    container_name: inclusion-prover
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - evm1
      - evm2
    restart: always
    env_file:
     - .env.example

