# The Licensed Work is (c) 2022 Sygma
# SPDX-License-Identifier: LGPL-3.0-only

name: Sygma Inclusion Prover

on:
  push:
    branches:
      - main

run-name: Deploy Inclusion-Prover to Testnet - ${{ inputs.release_tag }} by @${{ github.actor }}

env:
  ENVIRONMENT: 'TESTNET'
  REGISTRY: 'ghcr.io'
  TAG: 'latest'


jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    environment: testnet
    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout the source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to ghcr
        id: ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: build / tag / push docker image into ghcr
        id: build-and-push-tag
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.TAG }},${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }}

      - name: slack notify
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,job,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

          ######################## region 1 ########################
  deploy:
    needs: push
    name: deploy
    runs-on: ubuntu-latest
    environment: testnet
    permissions:
      contents: read
      id-token: write
    env: 
      AWS_TESTNET: '${{ secrets.AWS_TESTNET }}'
      AWS_REGION: '${{ secrets.AWS_REGION }}'
    steps:
      - name: checkout ecs repo
        uses: actions/checkout@v4
        with:
          repository: sygmaprotocol/devops
          token: ${{ secrets.GHCR_TOKEN }}

      - name: render jinja2 templates to task definition json files
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: 'inclusion-prover/ecs/task_definition-${{ env.ENVIRONMENT }}.j2'
          output_file: 'inclusion-prover/ecs/task_definition-${{ env.ENVIRONMENT }}.json'
          data_format: json
          variables: |
            awsAccountId=${{ env.AWS_TESTNET }}
            awsRegion=${{ env.AWS_REGION }}
            awsEfs=${{ secrets.INCLUSION_EFS }}
            imageTag=${{ github.ref_name }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_TESTNET }}:role/github-actions-${{ env.ENVIRONMENT }}-chainbridge
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GithubActions

      - name: deploy task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: 'inclusion-prover/ecs/task_definition-${{ env.ENVIRONMENT }}.json'
          service: 'inclusion-prover-service-${{ env.ENVIRONMENT }}'
          cluster: 'relayer-${{ env.ENVIRONMENT }}'
          wait-for-service-stability: true

      - name: slack notify
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,job,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
