# The Licensed Work is (c) 2023 Sygma
# SPDX-License-Identifier: LGPL-3.0-only

on: [pull_request]
name: License check
env:
  GO111MODULE: on 
  
jobs:
  license-check:
    runs-on: ubuntu-latest
    container: golang:1.19
    steps:
      - uses: actions/checkout@v2

      - run: go install github.com/google/addlicense@latest

      - run: make license-check